#!/ffp/bin/bash
# ----------------------------------------------
# Muninlite plugin for 
#  DNS-320, DNS-323 & DNS-325
#
# Get disks occupation level in %
#
# Only display real disks mounted under 
#  /mnt/HD_x2 or /mnt/HD/HD_x2
#
# 12/08/2014, V1.0 - Creation by N. Bernaerts
# ----------------------------------------------

# -------------------------------------------------------
# Initialisation
# -------------------------------------------------------

# set linefeed separator
IFS='
'

# list available drives (user disks are under HD_x2)
ARR_DISK=( $(df | grep "HD..2" | sed 's/ \+/|/g') )

# -------------------------------------------------------
# Handle configuration call
# -------------------------------------------------------

# config : read node configuration
if [ "$1" = "config" ]; then
  # display general information
  echo "graph_title Disk usage"
  echo "graph_vlabel Percentage"
  echo "graph_category system"
  echo "graph_scale no"
  echo "graph_args --lower-limit 0 --upper-limit 100"
  echo "graph_info This graph shows the usage level of disks in %"

  # loop thru disks array
  for DISK in "${ARR_DISK[@]}"
  do
    # retrieve disk information
    DISK_DEVICE=$(echo $DISK | cut -d'|' -f1 | sed 's/\/dev\///')
    DISK_SIZE=$(echo $DISK | cut -d'|' -f2)
    DISK_SIZE=$(expr $DISK_SIZE / 1048576)
    DISK_LEFT=$(echo $DISK | cut -d'|' -f4)
    DISK_LEFT=$(expr $DISK_LEFT / 1048576)
    DISK_MOUNT=$(echo $DISK | cut -d'|' -f6)

    # display disk information
    echo "$DISK_DEVICE.label $DISK_MOUNT"
    echo "$DISK_DEVICE.type GAUGE"
    echo "$DISK_DEVICE.draw LINE2"
    echo "$DISK_DEVICE.min 0"
    echo "$DISK_DEVICE.max 100"
    echo "$DISK_DEVICE.info $DISK_LEFT of $DISK_SIZE Gb available on /dev/$DISK_DEVICE"
  done

# -------------------------------------------------------
# Handle data read call
# -------------------------------------------------------

# normal case : get number of running instances for supervised processes
else
  # loop thru disks array
  for DISK in "${ARR_DISK[@]}"
  do
    # retrieve disk information
    DISK_DEVICE=$(echo $DISK | cut -d'|' -f1 | sed 's/\/dev\///')
    DISK_PERCENT=$(echo $DISK | cut -d'|' -f5 | sed 's/%//')

    # display disk information
    echo "$DISK_DEVICE.value $DISK_PERCENT"
  done

fi

# end
exit 0
