#!/ffp/bin/sh
# ----------------------------------------------
# Muninlite plugin for DNS-323
#
# Used to get uptime,
# while correcting the arm bug where uptime value is huge
# Uses idle uptime, which is quite accurate 
# on this type on NAS.
#
# To install these utilities, please check
# http://bernaerts.dyndns.org/nas/72-dns-323-ffp07/318-dns323-ffp7-snmp-supervise-temperature-case-hdd
#
# 31/07/2014, V1.0 - Creation by N. Bernaerts
# ----------------------------------------------

# -------------------------------------------------------
# Handle configuration call
# -------------------------------------------------------

# config : read node configuration
if [ "$1" = "config" ]; then
  echo "graph_title Uptime"
  echo "graph_args --base 1000 -l 0 "
  echo "graph_vlabel uptime in days"
  echo "graph_category system"
  echo "uptime.label uptime"
  echo "uptime.draw AREA"
  echo "uptime.cdef uptime,86400,/"

# -------------------------------------------------------
# Handle data read call
# -------------------------------------------------------

# normal case : read temperatures
else
  echo "uptime.value" $(cut -d\  -f2 /proc/uptime)

fi
