#!/ffp/bin/bash 
# ----------------------------------------------
# Muninlite plugin for DNS-325
# 
# Plugin to supervise UPS device
#  connected to DNS-325 USB port
# Tested with EATON 3S 550 UPS
#
# To install muninlite on DNS-325, please check :
#  http://bernaerts.dyndns.org/nas/71-dns325-ffp07/319-dns325-dns323-ffp7-munin-node-muninlite
#
# 07/05/2015, V1.0 - Creation by N. Bernaerts
# ----------------------------------------------

# -------------------------------------------------------
#   Initialisation
# -------------------------------------------------------

# get nas name
NAS_IP=$(hostname)

# -------------------------------------------------------
#   Configuration call
# -------------------------------------------------------

if [ "$1" = "config" ]; then

  # read UPS data
  UPS_MANUFACTURER=$(upsc usbhid ups.mfr)
  UPS_MODEL=$(upsc usbhid ups.model)
  UPS_POWER=$(upsc usbhid ups.power.nominal)
  UPS_BATTERY=$(upsc usbhid battery.type)
  UPS_STATUS=$(upsc usbhid ups.status | cut -d' ' -f1)

  # get UPS connection hostname
  echo "host_name $NAS_IP"

  # graph  description
  echo "graph_title UPS ${UPS_MANUFACTURER} model ${UPS_MODEL}"
  echo "graph_category power"
  echo "graph_info This graph shows UPS battery charge and load"
  echo "graph_args --upper-limit 100 -l 0 --rigid"

  # battery capacity
  echo "capacity.info Battery ${UPS_BATTERY} of ${UPS_POWER} VA"
  echo "capacity.label Battery level (%)"
  echo "capacity.draw AREA"
  [ "${UPS_STATUS}" = "OL" ] && echo "capacity.colour 008000" || echo "capacity.colour FFA500"
  echo "capacity.min 0"
  echo "capacity.max 100"

  # input power
  echo "power.info Input power"
  echo "power.label Input power (%)"
  echo "power.draw LINE2"
  echo "power.colour 0000FF"
  echo "power.min 0"

  # battery runtime
  echo "runtime.info UPS runtime if power failure"
  echo "runtime.label Runtime (mn)"
  echo "runtime.draw LINE2"
  echo "runtime.colour FF0000"
  echo "runtime.min 0"

# -------------------------------------------------------
#    Normal call : Read Data
# -------------------------------------------------------

else

  # read UPS data
  UPS_BATTERY=$(upsc usbhid battery.charge)
  UPS_LOAD=$(upsc usbhid ups.load)
  UPS_RUNTIME=$(($(upsc usbhid battery.runtime) / 60))

  # publish battery level and runtime
  echo "capacity.value ${UPS_BATTERY}"
  echo "power.value ${UPS_LOAD}"
  echo "runtime.value ${UPS_RUNTIME}"

fi
