#!/ffp/bin/bash
# ----------------------------------------------
# Muninlite plugin for DNS-323 & DNS-325
#
# Used to get number of instances of a running process.
# In case process is not running, a wake-up command can be run.
#
# 04/08/2014, V1.0 - Creation by N. Bernaerts
# ----------------------------------------------

# -------------------------------------------------------
# Initialisation
# -------------------------------------------------------

# declare list of processes to supervise
#  DISPLAY - Display name
#  PROCESS - Process name
#  RESTART - Restart command
ARR_DISPLAY=("RSync" "SNMP")
ARR_PROCESS=("rsync" "snmpd")
ARR_COMMAND=("/ffp/start/rsyncd.sh restart" "/ffp/start/snmpd.sh restart")

# -------------------------------------------------------
# Handle configuration call
# -------------------------------------------------------

# config : read node configuration
if [ "$1" = "config" ]; then

  # loop thru processes
  for ((i = 0; i < ${#ARR_PROCESS[@]}; i++))
  do
    echo "multigraph ${ARR_DISPLAY[$i]}"
    echo "graph_title ${ARR_DISPLAY[$i]}"
    echo "graph_vlabel Number of processes"
    echo "graph_category process"
    echo "graph_info This graph shows the number of ${ARR_PROCESS[$i]} processes running"
    echo "running.label ${ARR_DISPLAY[$i]}"
    echo "running.type GAUGE"
    echo "running.min 0"
    echo "running.critical 1:"
    echo "running.info If no instance is running, -> ${ARR_COMMAND[$i]} <- will be invoqued."
    echo "running.colour 0000ff"
  done

# -------------------------------------------------------
# Handle data read call
# -------------------------------------------------------

# normal case : get number of running instances for supervised processes
else
  # loop thru processes
  for ((i = 0; i < ${#ARR_PROCESS[@]}; i++))
  do
    # get number of running process instances
    NUMBER=`ps -ef 2>/dev/null | grep -v grep | grep -c ${ARR_PROCESS[$i]}`

    # display result
    echo "multigraph ${ARR_DISPLAY[$i]}"
    echo "running.value $NUMBER"

    # if no instance is running, run restart command
    [ "$NUMBER" = "0" ] && ${ARR_COMMAND[$i]} 1>/dev/null 2>/dev/null &
  done

fi

# end
exit 0
