#!/bin/bash
# -*- sh -*-
# ---------------------------------------------------------------
#  Munin plugin for Temperature & Humidity sensor model HWg-STE
#   http://www.hw-group.com/products/HWg-STE/STE_ip_temperature_sensor_en.html
#
#  Plugin uses the mobile web interface page 
#   available under /index_m.asp
#
#  Must be declared like an SMTP plugin with following 
#   plugin name format : hwgste_hostname 
#  where hostame is the sensor's hostname
#
#  Parameters :
#    $1 : none, "autoconf" or "config"
#
#  22/04/2015, V1.0 - Creation by N. Bernaerts
# ---------------------------------------------------------------

: << =cut

=head1 NAME

hwgste - Munin plugin to monitor temperature and humidity from sensor HWg-STE

=head1 APPLICABLE SYSTEMS

Any HWg-STE sensor

=head1 CONFIGURATION

None

=head1 INTERPRETATION

Temperature in Celcius and Humidity in relative percentage

=head1 MAGIC MARKERS

  #%# family=auto
  #%# capabilities=autoconf

=head1 VERSION

  $Id$

=head1 BUGS

None known.

=head1 AUTHOR

Copyright (C) 2015 Nicolas Bernaerts

=head1 LICENSE

GPLv2.

=cut

# -------------------------------------------------------
#  Retrieve sensor hostname from plugin name
#   -> hwgste_hostname 
# -------------------------------------------------------

# get sensor network name from script name
SENSOR_IP=$(basename $0 | cut -d'_' -f2)

# -------------------------------------------------------
#  Handle autoconf call
# -------------------------------------------------------

# answer is always YES
if [ "$1" = "autoconf" ]; then
  [ "${SENSOR_IP}" != "" ] && echo "yes" || echo "no (sensor hostname is not in the plugin name)"

# -------------------------------------------------------
#  Handle configuration call
# -------------------------------------------------------
elif [ "$1" = "config" ]; then
  # sensor general infos
  echo "host_name $SENSOR_IP"
  echo "graph_title Temperature and Humidity levels"
  echo "graph_vlabel Levels"
  echo "graph_category sensor"
  echo "graph_info This graph shows sensor temperature and humidity levels"

  # Temperature
  echo "temperature.info Temperature sensor"
  echo "temperature.label Temperature (Celcius)"
  echo "temperature.draw LINE2"

  # Humidity
  echo "humidity.info Humidity sensor"
  echo "humidity.label Humidity (%)"
  echo "humidity.draw LINE2"

# -------------------------------------------------------
#  Handle data read call
# -------------------------------------------------------
else
  # generate temporary file
  FILE_TMP=$(mktemp -t munin-sensor-XXXXXXXXXX.txt)

  # read mobile web page from sensor and keep lines with class and value keywords
  wget -q -O - http://${SENSOR_IP}/index_m.asp | grep "value" | grep "class" > ${FILE_TMP}

  # extract temperature
  TEMPERATURE=$(head -n 1 ${FILE_TMP} | sed "s/^.*id=.*>\([0-9\.]*\).*C.*$/\1/")

  # extract temperature
  HUMIDITY=$(tail -n 1 ${FILE_TMP} | sed "s/^.*id=.*>\([0-9\.]*\).*RH.*$/\1/")

  # delete temporary file
  rm ${FILE_TMP}

  # Publish data
  echo "temperature.value $TEMPERATURE"
  echo "humidity.value $HUMIDITY"
fi

exit 0
