#!/bin/bash 
# ----------------------------------------------
#
# Plugin to supervise UPS device connected to USB port
# UPS is connected to localhost
#
# Tested with EATON 3S 550 UPS
#
# 31/05/2015, V1.0 - Creation by N. Bernaerts
# ----------------------------------------------

# -------------------------------------------------------
#   Initialisation
# -------------------------------------------------------

# set name you've configured in /etc/nut/ups.conf
UPS_NAME="eaton"

# -------------------------------------------------------
#   Configuration call
# -------------------------------------------------------

if [ "$1" = "config" ]; then

  # read UPS data
  UPS_MANUFACTURER=$(upsc ${UPS_NAME}@localhost ups.mfr)
  UPS_MODEL=$(upsc ${UPS_NAME}@localhost ups.model)
  UPS_POWER=$(upsc ${UPS_NAME}@localhost ups.power.nominal)
  UPS_BATTERY=$(upsc ${UPS_NAME}@localhost battery.type)
  UPS_STATUS=$(upsc ${UPS_NAME}@localhost ups.status | cut -d' ' -f1)

  # get UPS connection hostname
  echo "host_name $NAS_IP"

  # graph  description
  echo "graph_title UPS ${UPS_MANUFACTURER} model ${UPS_MODEL}"
  echo "graph_category power"
  echo "graph_info This graph shows UPS battery charge and load"
  echo "graph_args --upper-limit 100 -l 0 --rigid"

  # battery capacity
  echo "capacity.info Battery ${UPS_BATTERY} of ${UPS_POWER} VA"
  echo "capacity.label Battery level (%)"
  echo "capacity.draw LINE2"
  [ "${UPS_STATUS}" = "OL" ] && echo "capacity.colour 008000" || echo "capacity.colour FFA500"
  echo "capacity.min 0"
  echo "capacity.max 100"

  # input power
  echo "power.info Input power"
  echo "power.label Input power (%)"
  echo "power.draw LINE1"
  echo "power.colour 0000FF"
  echo "power.min 0"

  # battery runtime
  echo "runtime.info UPS runtime if power failure"
  echo "runtime.label Runtime (mn)"
  echo "runtime.draw LINE1"
  echo "runtime.colour FF0000"
  echo "runtime.min 0"

# -------------------------------------------------------
#    Normal call : Read Data
# -------------------------------------------------------

else

  # read UPS data
  UPS_BATTERY=$(upsc ${UPS_NAME}@localhost battery.charge)
  UPS_LOAD=$(upsc ${UPS_NAME}@localhost ups.load)
  UPS_RUNTIME=$(($(upsc ${UPS_NAME}@localhost battery.runtime) / 60))

  # publish battery level and runtime
  echo "capacity.value ${UPS_BATTERY}"
  echo "power.value ${UPS_LOAD}"
  echo "runtime.value ${UPS_RUNTIME}"

fi
